#pragma once

#include <cstdint>

namespace types::enums {

enum class Ability : uint8_t {
    // clang-format off

    NONE,

    AIR_LOCK,     ARENA_TRAP,   BATTLE_ARMOR,  BLAZE,        CHLOROPHYLL,  CLEAR_BODY,
    CLOUD_NINE,   COLOR_CHANGE, COMPOUND_EYES, CUTE_CHARM,   DAMP,         DROUGHT,
    DRIZZLE,      EARLY_BIRD,   EFFECT_SPORE,  FLAME_BODY,   FLASH_FIRE,   FORECAST,
    GUTS,         HUGE_POWER,   HUSTLE,        HYPER_CUTTER, ILLUMINATE,   IMMUNITY,
    INNER_FOCUS,  INSOMNIA,     INTIMIDATE,    KEEN_EYE,     LEVITATE,     LIGHTNING_ROD,
    LIMBER,       LIQUID_OOZE,  MAGMA_ARMOR,   MAGNET_PULL,  MARVEL_SCALE, MINUS,
    NATURAL_CURE, OBLIVIOUS,    OVERGROW,      OWN_TEMPO,    PICKUP,       PLUS,
    POISON_POINT, PRESSURE,     PURE_POWER,    RAIN_DISH,    ROCK_HEAD,    ROUGH_SKIN,
    RUN_AWAY,     SAND_STREAM,  SAND_VEIL,     SERENE_GRACE, SHED_SKIN,    SHELL_ARMOR,
    SHIELD_DUST,  SOUNDPROOF,   SPEED_BOOST,   STATIC,       STENCH,       STICKY_HOLD,
    STURDY,       SUCTION_CUPS, SWARM,         SWIFT_SWIM,   SYNCHRONIZE,  TANGLED_FEET,
    THICK_FAT,    TORRENT,      TRACE,         TRUANT,       VITAL_SPIRIT, VOLT_ABSORB,
    WATER_ABSORB, WATER_VEIL,   WHITE_SMOKE,   WONDER_GUARD, SHADOW_TAG,

    // clang-format on
};

}  // namespace types::enums
