#pragma once

#include <cstdint>

namespace types::enums {

enum class Move : uint16_t {
    // clang-format off

    NONE,

    // === HIT (179) ===
    ABSORB,        ACID,          AEROBLAST,     AIR_CUTTER,   ANCIENT_POWER, ARM_THRUST,
    ASTONISH,      AURORA_BEAM,   BARRAGE,       BEAT_UP,      BIND,          BITE,
    BLAZE_KICK,    BLIZZARD,      BODY_SLAM,     BONEMERANG,   BONE_CLUB,     BONE_RUSH,
    BRICK_BREAK,   BUBBLE,        BUBBLE_BEAM,   BULLET_SEED,  CLAMP,         COMET_PUNCH,
    CONFUSION,     CONSTRICT,     COUNTER,       CRABHAMMER,   CROSS_CHOP,    CRUNCH,
    CRUSH_CLAW,    CUT,           DIZZY_PUNCH,   DOUBLE_EDGE,  DOUBLE_KICK,   DOUBLE_SLAP,
    DRAGON_BREATH, DRAGON_CLAW,   DRAGON_RAGE,   DREAM_EATER,  DRILL_PECK,    DYNAMIC_PUNCH,
    EARTHQUAKE,    EGG_BOMB,      EMBER,         ENDEAVOR,     ERUPTION,      EXPLOSION,
    EXTRASENSORY,  EXTREME_SPEED, FACADE,        FAKE_OUT,     FALSE_SWIPE,   FIRE_BLAST,
    FIRE_PUNCH,    FIRE_SPIN,     FISSURE,       FLAIL,        FLAMETHROWER,  FLAME_WHEEL,
    FRUSTRATION,   FURY_ATTACK,   FURY_CUTTER,   FURY_SWIPES,  GIGA_DRAIN,    GUILLOTINE,
    GUST,          HEADBUTT,      HEAT_WAVE,     HIDDEN_POWER, HI_JUMP_KICK,  HORN_ATTACK,
    HORN_DRILL,    HYDRO_PUMP,    HYPER_FANG,    HYPER_VOICE,  ICE_BALL,      ICE_BEAM,
    ICE_PUNCH,     ICICLE_SPEAR,  ICY_WIND,      IRON_TAIL,    JUMP_KICK,     KARATE_CHOP,
    LEAF_BLADE,    LEECH_LIFE,    LICK,          LOW_KICK,     LUSTER_PURGE,  MACH_PUNCH,
    MAGNITUDE,     MEGAHORN,      MEGA_DRAIN,    MEGA_KICK,    MEGA_PUNCH,    METAL_CLAW,
    METEOR_MASH,   MIRROR_COAT,   MIST_BALL,     MUDDY_WATER,  MUD_SHOT,      MUD_SLAP,
    NEEDLE_ARM,    NIGHT_SHADE,   OCTAZOOKA,     PECK,         PIN_MISSILE,   POISON_FANG,
    POISON_STING,  POISON_TAIL,   POUND,         POWDER_SNOW,  PRESENT,       PSYBEAM,
    PSYCHIC,       PSYWAVE,       PURSUIT,       QUICK_ATTACK, RAZOR_LEAF,    RETURN,
    REVENGE,       REVERSAL,      ROCK_BLAST,    ROCK_SLIDE,   ROCK_SMASH,    ROCK_THROW,
    ROCK_TOMB,     ROLLING_KICK,  ROLLOUT,       SACRED_FIRE,  SAND_TOMB,     SCRATCH,
    SECRET_POWER,  SEISMIC_TOSS,  SELF_DESTRUCT, SHADOW_BALL,  SHEER_COLD,    SIGNAL_BEAM,
    SILVER_WIND,   SKY_UPPERCUT,  SLAM,          SLASH,        SLUDGE,        SLUDGE_BOMB,
    SMELLING_SALT, SMOG,          SONIC_BOOM,    SPARK,        SPIKE_CANNON,  STEEL_WING,
    STOMP,         STRENGTH,      STRUGGLE,      SUBMISSION,   SUPER_FANG,    SURF,
    TACKLE,        TAKE_DOWN,     THUNDER,       THUNDERBOLT,  THUNDER_PUNCH, THUNDER_SHOCK,
    TRIPLE_KICK,   TRI_ATTACK,    TWINEEDLE,     TWISTER,      VICE_GRIP,     VINE_WHIP,
    VITAL_THROW,   VOLT_TACKLE,   WATERFALL,     WATER_GUN,    WATER_PULSE,   WATER_SPOUT,
    WEATHER_BALL,  WHIRLPOOL,     WING_ATTACK,   WRAP,         ZAP_CANNON,

    // === STAT (43) ===
    ACID_ARMOR,    AGILITY,      AMNESIA,      BARRIER,      BELLY_DRUM,  BULK_UP,      CALM_MIND,
    CHARM,         COSMIC_POWER, COTTON_SPORE, DEFENSE_CURL, DOUBLE_TEAM, DRAGON_DANCE, FAKE_TEARS,
    FEATHER_DANCE, FLASH,        FLATTER,      FOCUS_ENERGY, GROWL,       GROWTH,       HARDEN,
    HAZE,          HOWL,         IRON_DEFENSE, KINESIS,      LEER,        MEDITATE,     METAL_SOUND,
    MINIMIZE,      PSYCH_UP,     SAND_ATTACK,  SCARY_FACE,   SCREECH,     SHARPEN,      SMOKESCREEN,
    STRING_SHOT,   SWAGGER,      SWEET_SCENT,  SWORDS_DANCE, TAIL_GLOW,   TAIL_WHIP,    TICKLE,
    WITHDRAW,

    // === STATUS (38) ===
    AROMATHERAPY,  ATTRACT,     CONFUSE_RAY, CURSE,        DISABLE,       ENCORE,       GLARE,
    GRASS_WHISTLE, HEAL_BELL,   HYPNOSIS,    LEECH_SEED,   LOVELY_KISS,   MILK_DRINK,   MOONLIGHT,
    MORNING_SUN,   NIGHTMARE,   PAIN_SPLIT,  POISON_GAS,   POISON_POWDER, RECOVER,      REFRESH,
    REST,          SING,        SLACK_OFF,   SLEEP_POWDER, SOFT_BOILED,   SPITE,        SPORE,
    STUN_SPORE,    SUPERSONIC,  SWEET_KISS,  SYNTHESIS,    TAUNT,         THUNDER_WAVE, TORMENT,
    TOXIC,         WILL_O_WISP, YAWN,

    // === FIELD (26) ===
    DETECT,     DOOM_DESIRE,  ENDURE,     FOLLOW_ME,   FUTURE_SIGHT, HAIL,    INGRAIN,
    KNOCK_OFF,  LIGHT_SCREEN, MAGIC_COAT, MIST,        MUD_SPORT,    PROTECT, RAIN_DANCE,
    RAPID_SPIN, RECYCLE,      REFLECT,    SAFEGUARD,   SANDSTORM,    SNATCH,  SPIKES,
    SUBSTITUTE, SUNNY_DAY,    TRICK,      WATER_SPORT, WISH,

    // === COMPOSITE (68) ===
    AERIAL_ACE,   ASSIST,       BATON_PASS, BIDE,         BLAST_BURN,  BLOCK,        BOUNCE,
    CAMOUFLAGE,   CHARGE,       CONVERSION, CONVERSION_2, COVET,       DESTINY_BOND, DIG,
    DIVE,         FAINT_ATTACK, FLY,        FOCUS_PUNCH,  FORESIGHT,   FRENZY_PLANT, GRUDGE,
    HELPING_HAND, HYDRO_CANNON, HYPER_BEAM, IMPRISON,     LOCK_ON,     MAGICAL_LEAF, MEAN_LOOK,
    MEMENTO,      METRONOME,    MIMIC,      MIND_READER,  MIRROR_MOVE, NATURE_POWER, ODOR_SLEUTH,
    OUTRAGE,      OVERHEAT,     PAY_DAY,    PERISH_SONG,  PETAL_DANCE, PSYCHO_BOOST, RAGE,
    RAZOR_WIND,   ROAR,         ROLE_PLAY,  SHADOW_PUNCH, SHOCK_WAVE,  SKETCH,       SKILL_SWAP,
    SKULL_BASH,   SKY_ATTACK,   SLEEP_TALK, SNORE,        SOLAR_BEAM,  SPIDER_WEB,   SPIT_UP,
    SPLASH,       STOCKPILE,    SUPERPOWER, SWALLOW,      SWIFT,       TEETER_DANCE, TELEPORT,
    THIEF,        THRASH,       TRANSFORM,  UPROAR,       WHIRLWIND,

    // clang-format on
};

}  // namespace types::enums
